#ifndef ZMS_SESSION_RTMP_H
#define ZMS_SESSION_RTMP_H

#include <stdint.h>

#define ZMS_RTMP_DEFAULT_CHUNK 128
#define ZMS_RTMP_HANDSHAKE_RANDOM 1528

#define ZMS_RTMP_MSG_SET_CHUNK 1
#define ZMS_RTMP_MSG_ACK 3
#define ZMS_RTMP_MSG_USER_CONTROL 4
#define ZMS_RTMP_MSG_WIN_SIZE 5
#define ZMS_RTMP_MSG_SET_PEER_BW 6
#define ZMS_RTMP_MSG_AUDIO 8
#define ZMS_RTMP_MSG_VIDEO 9

/** FLV/RTMP SoundFormat（首字节高 4 bit） */
#define ZMS_RTMP_SOUND_FMT_G711A 7
#define ZMS_RTMP_SOUND_FMT_G711U 8
#define ZMS_RTMP_SOUND_FMT_AAC 10
#define ZMS_RTMP_MSG_DATA 18
#define ZMS_RTMP_MSG_CMD 20

#define ZMS_RTMP_CHUNK_SYSTEM 3
#define ZMS_RTMP_CHUNK_MEDIA 8

#endif /* ZMS_SESSION_RTMP_H */
