# ZMS sources — aligned with src/ layout
set(ZMS_SOURCES
    src/vod/io/vod_thread_pool.c
    src/util/buf_pool.c
    src/util/poller_drain.c
    src/ops/service/config.c
    src/ops/server/zms_server.c
    src/util/log_throttle.c
    src/util/crypto/md5.c
    src/util/crypto/sha1.c
    src/util/hex_decode.c
    src/ops/service/pull_ssl.c
    src/ops/api/json/media_json.c
    src/ops/api/webapi/webapi.c
    src/ops/api/webapi/webapi_http_handler.c
    src/ops/api/webhook/webhook_client.c
    src/live/play/dash/http_dash_sidecar.c
    src/live/play/dash/http_dash_serve.c
    src/live/play/dash/http_dash_route.c
    src/live/play/dash/http_dash_playlist.c
    src/live/play/dash/http_dash_segmenter.c
    src/egress/egress_sidecar_param_sets.c
    src/live/play/hls/http_hls_sidecar.c
    src/live/play/hls/http_hls_route.c
    src/live/play/hls/http_hls_serve.c
    src/live/play/hls/http_hls_playlist.c
    src/live/play/hls/http_hls_segmenter.c
    src/live/play/hls/http_hls_fmp4_writer.c
    src/live/play/hls/http_hls_ts_writer.c
    src/live/proxy/live_pull_proxy.c
    src/live/ingest/codec/aac_ingest.c
    src/media/codec/aac/aac_config.c
    src/media/codec/aac/aac_over_rtmp.c
    src/media/codec/aac/aac_over_rtp.c
    src/media/codec/bitstream/annexb.c
    src/media/codec/av1/av1_over_rtp.c
    src/media/codec/av1/av1_over_rtmp.c
    src/media/codec/codec_id.c
    src/live/ingest/codec/g711_ingest.c
    src/media/codec/g711/g711_over_rtp.c
    src/media/codec/g711/g711_over_rtmp.c
    src/media/codec/h264/h264_config.c
    src/media/codec/h264/h264_es.c
    src/live/ingest/codec/h264_ingest.c
    src/media/codec/h264/h264_over_rtmp.c
    src/media/codec/h264/h264_over_rtp.c
    src/media/codec/h264/h264_sps.c
    src/media/codec/h265/h265_config.c
    src/media/codec/h265/h265_es.c
    src/live/ingest/codec/h265_ingest.c
    src/media/codec/h265/h265_over_rtmp.c
    src/media/codec/h266/h266_over_rtmp.c
    src/media/codec/h265/h265_over_rtp.c
    src/media/codec/payload/payload_rtp_register.c
    src/media/codec/payload/payload_rtp_librtp.c
    src/media/codec/vpx/vpx_over_rtmp.c
    src/engine/media_clock.c
    src/engine/frame.c
    src/engine/stream/stream_url.c
    src/session/codec_filter.c
    src/engine/gop/gop_queue.c
    src/engine/gop/gop_reader_seek.c
    src/engine/stream/stream_stats.c
    src/engine/stream_track.c
    src/engine/media_event.c
    src/live/ingest/common/stream_ingest.c
    src/live/ingest/common/codec_dispatch.c
    src/egress/egress_pacing.c
    src/egress/egress_source.c
    src/live/ingest/common/protocol_opts.c
    src/egress/egress_segment_recorder.c
    src/egress/egress_mp4_recorder.c
    src/engine/stream/stream_hub.c
    src/media/container/flv/flv_wire.c
    src/live/play/http_flv/http_flv_muxer.c
    src/media/container/flv/flv_file_muxer.c
    src/media/wire/rtp_packet.c
    src/media/container/flv/flv_tag_container_demux.c
    src/media/container/flv/flv_tag_probe.c
    src/media/container/flv/flv_tag_demuxer.c
    src/media/container/flv/flv_tag_framer.c
    src/media/container/flv/flv_file_demuxer.c
    src/media/container/mkv/mkv_demuxer.c
    src/media/container/flv/flv_tag_pack.c
    src/egress/rtp/rtp_muxer.c
    src/egress/rtp/rtp_muxer_paramsets.c
    src/media/container/hls/hls_playlist.c
    src/media/container/hls/hls_fmp4.c
    src/media/container/mp4/mp4_demuxer.c
    src/media/container/mpegts/mpegts_continuous_muxer.c
    src/media/container/mpegts/mpegts_demuxer.c
    src/media/container/mpegts/mpegts_mux_feed.c
    src/egress/mpegts/mpegts_egress.c
    src/media/container/mpegts/mpegts_segment_muxer.c
    src/media/container/mpegps/mpegps_demuxer.c
    src/live/publish/rtp_ps_dispatch.c
    src/session/srt/srt_streamid.c
    src/media/container/container_registry.c
    src/session/rtsp/rtsp_interleaved.c
    src/media/container/demux_pipeline.c
    src/egress/egress_pipeline.c
    src/egress/egress_live_policy.c
    src/media/codec/frame_policy/frame_codec_policy.c
    src/media/codec/payload/payload_registry.c
    src/media/codec/payload/payload_track.c
    src/session/session_dispatcher.c
    src/session/play_binding.c
    src/engine/module_registry.c
    src/session/http/http_hls_client.c
    src/session/http/http_flv_client.c
    src/session/http/websocket/websocket_handshake.c
    src/session/http/websocket/websocket_framer.c
    src/session/http/http_service.c
    src/session/http/http_router.c
    src/live/play/http_flv/http_flv_serve.c
    src/live/play/http_flv/http_flv_route.c
    src/live/play/http_ts/http_ts_route.c
    src/live/play/http_ts/http_ts_dispatch.c
    src/session/http/http_message_framer.c
    src/session/http/http_parser.c
    src/session/http/http_dispatch.c
    src/session/http/http_route_path.c
    src/session/http/http_response.c
    src/session/http/http_request_reader.c
    src/live/proxy/player.c
    src/vod/play/vod_http_serve.c
    src/session/rtmp/rtmp_amf.c
    src/session/rtmp/rtmp_amf3_decode.c
    src/session/rtmp/rtmp_client.c
    src/session/rtmp/rtmp_handshake.c
    src/session/rtmp/rtmp_hs_crypto.c
    src/session/rtmp/rtmp_protocol.c
    src/session/rtmp/rtmp_protocol_chunk_read.c
    src/session/rtmp/rtmp_protocol_chunk_write.c
    src/session/rtmp/rtmp_protocol_control.c
    src/session/rtmp/rtmp_protocol_handshake.c
    src/session/rtmp/rtmp_protocol_rx.c
    src/session/rtmp/rtmp_dispatch.c
    src/session/rtmp/rtmp_protocol_util.c
    src/session/rtmp/rtmp_service.c
    src/session/rtmp/rtmp_session.c
    src/session/rtmp/rtmp_session_common.c
    src/live/play/rtmp_live_play_session.c
    src/vod/play/vod_rtmp_play_session.c
    src/live/publish/rtmp_ingest_session.c
    src/session/rtp/rtp_receiver.c
    src/session/rtp/rtp_ps_server.c
    src/session/rtp/rtcp.c
    src/session/rtsp/rtsp_client.c
    src/session/rtsp/rtsp_client_udp.c
    src/session/rtsp/rtsp_digest.c
    src/session/rtsp/rtsp_parser.c
    src/egress/rtp/rtp_play_pump.c
    src/egress/egress_clock.c
    src/session/rtsp/rtsp_dispatch.c
    src/session/rtsp/rtsp_service.c
    src/live/publish/rtsp_announce_session.c
    src/session/rtsp/rtsp_session_auth.c
    src/session/rtsp/rtsp_session_common.c
    src/session/rtsp/rtsp_session_ctrl.c
    src/session/rtsp/rtsp_session_describe.c
    src/session/rtsp/rtsp_session.c
    src/session/rtsp/rtsp_session_play.c
    src/session/rtsp/rtsp_session_rtcp.c
    src/session/rtsp/rtsp_session_vod.c
    src/live/publish/rtsp_record_session.c
    src/session/rtsp/rtsp_session_setup.c
    src/session/rtsp/rtsp_session_udp.c
    src/session/rtsp/rtsp_splitter.c
    src/session/rtsp/rtsp_transport.c
    src/session/rtsp/rtsp_sdp.c
    src/vod/io/vod_mov_file_buffer.c
    src/vod/io/vod_mkv_file_buffer.c
    src/vod/io/vod_format.c
    src/vod/io/vod_reader.c
    src/vod/io/mp4_vod_reader.c
    src/vod/io/vod_flv_metadata.c
    src/vod/play/vod_flv_muxer.c
    src/vod/io/vod_codec_ext.c
    src/vod/io/vod_buffer.c
    src/vod/io/vod_flv_cache.c
    src/vod/io/vod_flv_index.c
    src/vod/play/vod_hls.c
    src/vod/play/vod_play_lane.c
    src/vod/io/vod_source.c
)
